[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
  -D TAG='"Arduino"'
  -D USE_ESP_IDF_LOG
lib_deps =
  SensESP
  adafruit/Adafruit INA219 @ ^1.2.3
