[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
  SensESP
  adafruit/Adafruit INA219 @ ^1.2.3
  khoih-prog/ESPAsync_WiFiManager @ ^1.15.0
